/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrafficLightRouteImport } from './routes/traffic-light'
import { Route as TicTacToeRouteImport } from './routes/tic-tac-toe'
import { Route as StopwatchRouteImport } from './routes/stopwatch'
import { Route as RockPaperScissorsRouteImport } from './routes/rock-paper-scissors'
import { Route as QuoteGeneratorRouteImport } from './routes/quote-generator'
import { Route as GradientRouteImport } from './routes/gradient'
import { Route as DiceRouteImport } from './routes/dice'
import { Route as IndexRouteImport } from './routes/index'

const TrafficLightRoute = TrafficLightRouteImport.update({
  id: '/traffic-light',
  path: '/traffic-light',
  getParentRoute: () => rootRouteImport,
} as any)
const TicTacToeRoute = TicTacToeRouteImport.update({
  id: '/tic-tac-toe',
  path: '/tic-tac-toe',
  getParentRoute: () => rootRouteImport,
} as any)
const StopwatchRoute = StopwatchRouteImport.update({
  id: '/stopwatch',
  path: '/stopwatch',
  getParentRoute: () => rootRouteImport,
} as any)
const RockPaperScissorsRoute = RockPaperScissorsRouteImport.update({
  id: '/rock-paper-scissors',
  path: '/rock-paper-scissors',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteGeneratorRoute = QuoteGeneratorRouteImport.update({
  id: '/quote-generator',
  path: '/quote-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const GradientRoute = GradientRouteImport.update({
  id: '/gradient',
  path: '/gradient',
  getParentRoute: () => rootRouteImport,
} as any)
const DiceRoute = DiceRouteImport.update({
  id: '/dice',
  path: '/dice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dice': typeof DiceRoute
  '/gradient': typeof GradientRoute
  '/quote-generator': typeof QuoteGeneratorRoute
  '/rock-paper-scissors': typeof RockPaperScissorsRoute
  '/stopwatch': typeof StopwatchRoute
  '/tic-tac-toe': typeof TicTacToeRoute
  '/traffic-light': typeof TrafficLightRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dice': typeof DiceRoute
  '/gradient': typeof GradientRoute
  '/quote-generator': typeof QuoteGeneratorRoute
  '/rock-paper-scissors': typeof RockPaperScissorsRoute
  '/stopwatch': typeof StopwatchRoute
  '/tic-tac-toe': typeof TicTacToeRoute
  '/traffic-light': typeof TrafficLightRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dice': typeof DiceRoute
  '/gradient': typeof GradientRoute
  '/quote-generator': typeof QuoteGeneratorRoute
  '/rock-paper-scissors': typeof RockPaperScissorsRoute
  '/stopwatch': typeof StopwatchRoute
  '/tic-tac-toe': typeof TicTacToeRoute
  '/traffic-light': typeof TrafficLightRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dice'
    | '/gradient'
    | '/quote-generator'
    | '/rock-paper-scissors'
    | '/stopwatch'
    | '/tic-tac-toe'
    | '/traffic-light'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dice'
    | '/gradient'
    | '/quote-generator'
    | '/rock-paper-scissors'
    | '/stopwatch'
    | '/tic-tac-toe'
    | '/traffic-light'
  id:
    | '__root__'
    | '/'
    | '/dice'
    | '/gradient'
    | '/quote-generator'
    | '/rock-paper-scissors'
    | '/stopwatch'
    | '/tic-tac-toe'
    | '/traffic-light'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiceRoute: typeof DiceRoute
  GradientRoute: typeof GradientRoute
  QuoteGeneratorRoute: typeof QuoteGeneratorRoute
  RockPaperScissorsRoute: typeof RockPaperScissorsRoute
  StopwatchRoute: typeof StopwatchRoute
  TicTacToeRoute: typeof TicTacToeRoute
  TrafficLightRoute: typeof TrafficLightRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traffic-light': {
      id: '/traffic-light'
      path: '/traffic-light'
      fullPath: '/traffic-light'
      preLoaderRoute: typeof TrafficLightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tic-tac-toe': {
      id: '/tic-tac-toe'
      path: '/tic-tac-toe'
      fullPath: '/tic-tac-toe'
      preLoaderRoute: typeof TicTacToeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stopwatch': {
      id: '/stopwatch'
      path: '/stopwatch'
      fullPath: '/stopwatch'
      preLoaderRoute: typeof StopwatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rock-paper-scissors': {
      id: '/rock-paper-scissors'
      path: '/rock-paper-scissors'
      fullPath: '/rock-paper-scissors'
      preLoaderRoute: typeof RockPaperScissorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote-generator': {
      id: '/quote-generator'
      path: '/quote-generator'
      fullPath: '/quote-generator'
      preLoaderRoute: typeof QuoteGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gradient': {
      id: '/gradient'
      path: '/gradient'
      fullPath: '/gradient'
      preLoaderRoute: typeof GradientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dice': {
      id: '/dice'
      path: '/dice'
      fullPath: '/dice'
      preLoaderRoute: typeof DiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiceRoute: DiceRoute,
  GradientRoute: GradientRoute,
  QuoteGeneratorRoute: QuoteGeneratorRoute,
  RockPaperScissorsRoute: RockPaperScissorsRoute,
  StopwatchRoute: StopwatchRoute,
  TicTacToeRoute: TicTacToeRoute,
  TrafficLightRoute: TrafficLightRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
